apiVersion: v1
kind: Service
metadata:
  name: lacework-kubernetes-security-demo
  labels:
    app: lacework-kubernetes-security-demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: lacework-kubernetes-security-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lacework-kubernetes-security-demo
  labels:
    app: lacework-kubernetes-security-demo
spec:
  selector:
    matchLabels:
      app: lacework-kubernetes-security-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: lacework-kubernetes-security-demo
    spec:
      containers:
        - name: lacework-kubernetes-security-demo
          # image: ghcr.io/timarenz/lacework-kubernetes-security-demo:latest
          image: ghcr.io/timarenz/lacework-kubernetes-security-demo:v0.0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
