name: commit
on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Write release version to file
        run: echo ${{ steps.meta.outputs.version }}>${GITHUB_WORKSPACE}/app/static/version.txt

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan for vulnerabilities with Lacework
        uses: timarenz/lw-scanner-action@v0.5.1
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ steps.meta.outputs.version }}
          SCAN_LIBRARY_PACKAGES: true
          SAVE_RESULTS_IN_LACEWORK: false
          USE_POLICY: true

      - name: Scan kubernetes manifest
        env:
          SOLUBLE_ORG_ID: ${{ secrets.SOLUBLE_ORG_ID }}
          SOLUBLE_API_TOKEN: ${{ secrets.SOLUBLE_API_TOKEN }}
        run: |
          - curl https://raw.githubusercontent.com/soluble-ai/soluble-cli/master/linux-install.sh | sh
          - soluble kubernetes-scan --upload
