name: scan

on:
  push:
  workflow_call:
    secrets:
      LW_ACCOUNT_NAME:
        required: true
      LW_ACCESS_TOKEN:
        required: true
      SOLUBLE_ORG_ID:
        required: true
      SOLUBLE_API_TOKEN:
        required: true
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan for vulnerabilities with Lacework
        uses: timarenz/lw-scanner-action@v0.5.1
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_SCANNER_SAVE_RESULTS: true
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ steps.meta.outputs.version }}
          SCAN_LIBRARY_PACKAGES: true
          USE_POLICY: true

      - name: Scan kubernetes manifest
        env:
          SOLUBLE_ORG_ID: ${{ secrets.SOLUBLE_ORG_ID }}
          SOLUBLE_API_TOKEN: ${{ secrets.SOLUBLE_API_TOKEN }}
        run: |
          curl https://raw.githubusercontent.com/soluble-ai/soluble-cli/master/linux-install.sh | sh
          soluble kubernetes-scan --upload
